### ISSUE TITLE
Road map for running and monitoring job on karst

### ISSUE THREAD

**Issue by ajinkya-dhamnaskar** [airavata-courses/TeamAlpha#1]
Understanding and road map for Milestone 1;
1. Connect to karst through java using ssh keys (password less login).
2. Go to the destined directory.
3. Transfer code file (for eg test.c) from local system to server.
4. Compile code file on server remotely.
5. Transfer shell script file to schedule job on server.
6. Run shell file and get id of the scheduled job.
7. Keep polling to get status of the job submitted.
8. Once status of the job changes to "Completed" get output for the job from output file associated with the job.

Parameters Expected from end user:
1. Username.
2. ssh private key absolute path (for which public key is already there on the server).
3. Password for the private key if given.
4. code file absolute path.
5. Polling time to check job staus.

**Comment by smarru** [comment]
This is great outline and pretty much covers the project milestone 1 goals. Note, if you have trouble compiling codes on the server, you can skip that step and assume a binary exists. But you will still need the funcationality of moving a shell script or input files required for scientific applications.

**Comment by marpierc** [comment]
Yes, a bash command like ls, host name, or sleep is fine for this week.

Marlon
