### ISSUE TITLE
Pbs Script 

### ISSUE THREAD

**Issue by sanketmhaiskar** [airavata-courses/TeamAlpha#11]
Just a doubt,  is PBS Script making use of the config properties ? Wall time does not seem to go through. Also just a suggestion or may be a future addon , to provide the user with the functionality for job status notifications via email or on demand polling.

**Comment by amrutakamat16** [comment]
Yes Sanket.. The PBS script is using all values from the server.properties file. It takes walltime from the properties file too.
And thanks for your suggestion Sanket, we are planning to use a better way to monitor status of the submitted jobs when we convert the application into an api.
