### ISSUE TITLE
Job notification to user via email

### ISSUE THREAD

**Issue by pratishmerchant** [airavata-courses/TeamAlpha#12]
Currently the job monitoring is done via polling . Incase the job gets executed after the timeout period of polling or session is closed , there is no other way to notify user of job start or completion.

My suggestion would be to notify user via email when job is submiited. This will help user know the start , end and aborts irrespective of polling.

**Comment by ajinkya-dhamnaskar** [comment]
To deal with such jobs we had decided to have different thread. So, one thread would just submit the job and store job ids locally and other thread would use that store to monitor all the submitted jobs.
When we will convert this into api, we are panning to use better way to monitor status of the submitted jobs.
Thank you for your suggestion.

**Comment by abhijitkaranjkar89** [comment]
Don't you think it is a bit out of scope for 1st milestone.
Though will keep that in mind for future improvements.
Thank you
