### ISSUE TITLE
Project design suggestions

### ISSUE THREAD

**Issue by anujbhan** [airavata-courses/TeamAlpha#14]
It is more of an design constraint, the existing tool wouldn't allow the user to schedule multiple jobs.

**Comment by abhijitkaranjkar89** [comment]
Anuj Could you please explain in detail.
As far as we know, our application will allow running multiple jobs running multiple jars in parallel. Though user has to take care of other scenarios like changing the name of .txt file.

**Comment by anujbhan** [comment]
1. Yes, it is true. The application will indeed run multiple jobs, but will it be good design choice.
2. I agree the title of this issue will become irrelevant after your concerned reply, In my perspective keeping multiple JVM's running and also keeping multiple SSH session open until the job is finished will not scale. 

These are just suggestions, You have indeed implemented the project very well.
