### ISSUE TITLE
Please submit Milestone 2 to Canvas

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/TeamAlpha#22]
Hi Team Alpha,

If you are ready for me to grade your Milestone 2 branch, please submit it via Canvas so that I can assign a grade.

Thanks,

**Comment by ajinkya-dhamnaskar** [comment]
Hello Marlon,

We were trying to submit the git link for milestone 2 on 9th Feb itself.
But canvas does not have link for the same. Could you please suggest the
way to submit the same.

On Mon, Feb 15, 2016 at 1:55 PM, Marlon Pierce notifications@github.com
wrote:

> Hi Team Alpha,
> 
> If you are ready for me to grade your Milestone 2 branch, please submit it
> via Canvas so that I can assign a grade.
> 
> Thanks,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airavata-courses/TeamAlpha/issues/22.

## 

Thanks and regards,
Ajinkya Dhamnaskar
+18123695416

**Comment by marpierc** [comment]
Please try it again and let me know if it works or not.

**Comment by patel99** [comment]
Hi Marlon,
 I just logged in to canvas and I could not find project milestone 2 in assignment section of canvas.

**Comment by marpierc** [comment]
Try it now.
