### ISSUE TITLE
Need Milestone 2 instructions

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/TeamAlpha#23]
You need to add instructions that tell me how to run the assignment.

**Comment by patel99** [comment]
Hi Marlon,

Instructions for milestone 2 were kept in 'Instructions' folder in project. But for convenience I have created  a wiki page for the same. Below is the link of wiki page

https://github.com/airavata-courses/TeamAlpha/wiki/2.-Project-Milestone-2:-Details-and-Instructions

**Comment by marpierc** [comment]
Please add instructions for running without using Eclipse.

**Comment by patel99** [comment]
Hi Marlon,

We have following ideas to run this project without Eclipse,
1. We could host our web server on VM, and then anyone could directly hit the URL to get access to our application
2. Someone could run the server on their localhost itself, but this would require tomcat.
3. Or we could connect to IUSecure and run server on our machine & then we can publish our temporary IP address so that anyone could connect to that IP to access the application.

Which idea would work for you right now?

**Comment by marpierc** [comment]
#2 is the best option. I will be testing VM access on Jetstream for Tuesday.

For now you can solve this problem with instructions: “Marlon, download Tomcat x.y.z, unpack it and put the WAR created by Maven in webapps”.  In future versions, once we have the VM ready, you should provide a way to completely populate a vanilla VM automatically with a deployment mechanism. There are many tools that can do this.

Marlon

**Comment by ajinkya-dhamnaskar** [comment]
Hello Marlon,

For time being we have hosted an application on local system. You could access the same through Pulse Secure on http://140.182.28.59:8080/Airavata_Remote_Job_Runner/test.htm
We are yet to consider and incorporate security and other aspects to the system. The focus was to demonstrate asked functionalities. The system will evolve in successive releases. 

Sorry for caused inconvenience.

**Comment by marpierc** [comment]
That’s not the intention of the assignment. I don’t mind installing tomcat, for example, to grade the current milestone.

The point of all these assignments is to teach you to completely expose the full develop-build-test-deploy-update lifecycle through automation.

Marlon

**Comment by amrutakamat16** [comment]
Hello Marlon,

Sorry for the inconvenience. This time we did not have environment to create and setup the system. 
Next time we will make sure to stand up to your expectations.

**Comment by marpierc** [comment]
Team Alpha,

Please provide complete, step by step instructions for me to install and test your assignment.  As I said, I have no complaints installing Tomcat, etc for this assignment, but you need to tell me exactly what I need to do in one instruction file.  Don't make me guess.

**Comment by patel99** [comment]
Hi Marlon,

We have updated our wiki page with instructions on how to deploy the war file. The instructions can be found at https://github.com/airavata-courses/TeamAlpha/wiki/2.-Project-Milestone-2:-Details-and-Instructions

There are few constrains with this WAR file:
1. You should keep your private key at '~/.ssh'
2. Your private key file should be named 'id_rsa'
3. Your private key should not have any passphrase
4. Remote file path is '/N/dc2/scratch/marpierc/job-submission'. Your shell script would be generated at this path. Make sure to create 'job-submission' folder.

If this does not work well with you, then kindly share with us,
Your private key path with name of your file, private key file passphrase.
