### ISSUE TITLE
Milestone 3: Need DB set up instructions

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/TeamAlpha#25]
Please add instructions on how to setup the database.  Even better, you could automate this.

**Comment by abhijitkaranjkar89** [comment]
Hello Professor,
By "automate this", are you suggesting to add JPA framework and let the persistence.xml file handle everything?

**Comment by marpierc** [comment]
No, let’s stick with manual instructions. Post-midterm, your assignment will be to automate the entire setup so that deployment is all automated.

Marlon

**Comment by patel99** [comment]
I have updated the instructions at - https://github.com/airavata-courses/TeamAlpha/wiki/3.-Project-Milestone-3:-Details-and-Instructions
