### ISSUE TITLE
Milestone 3 Final Issues

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/TeamAlpha#27]
Hi Team Alpha,

As discussed, you can wrap up Milestone 3 by resolving these issue:
- Make sure you are loading the correct GROMACS module for the mdrun command that you want to use.
- GROMACS needs two inputs (see the class announcement), so you need to support multiple file uploads.
- Fix the DB setup so that it checks to see if the postgres user exists and creates it if not.

**Comment by patel99** [comment]
Hi Marlon,

We wanted to let you know that we have fixed these issues and you may now go ahead with grading Milestone-3
