### ISSUE TITLE
CI/CD Tool Discussion 

### ISSUE THREAD

**Issue by ajinkya-dhamnaskar** [airavata-courses/TeamAlpha#31]

**Comment by ajinkya-dhamnaskar** [comment]
Hello Suresh.
Could you please provide us admin access for TeamAlpha repository?
We are tying to setup Travis.

Ajinkya.

**Comment by patel99** [comment]
I am looking into Jenkins, would send out review shortly

**Comment by abhijitkaranjkar89** [comment]
Working on Docker tool. Trying to get a collective image of all required applications.

**Comment by patel99** [comment]
Hi Marlon/Suresh,

I tried to build and deploy using Jenkins, But when I try to copy war file to Hetstream VM, i get permission denied error, I tried to use 'chmod 700' to give write permission on remote directory bu problem still persists. Any comment on this?

![image](https://cloud.githubusercontent.com/assets/16781624/14274596/4ae2b3ca-fae0-11e5-8201-179e2d30fbb6.png)

**Comment by smarru** [comment]
Hi Ajinkya,

Now all of you are admin’s on this repo. So you should be able to setup Travis.

Suresh

**Comment by amrutakamat16** [comment]
Hello,

After looking into various tools like Jenkins, Travis, Docker and Puppet, we finally decided to go with Jenkins for CI.
