### ISSUE TITLE
Jetstream VM is not getting activated

### ISSUE THREAD

**Issue by patel99** [airavata-courses/TeamAlpha#32]
Hi Suresh/Marlon,

I requested a VM yesterday night, but its status is till 'Active - Networking'. I did try to create another instance, but it still gets stuck at Networking stage

![image](https://cloud.githubusercontent.com/assets/16781624/14322022/6d289fb2-fbe9-11e5-86c8-5784642697a6.png)

**Comment by marpierc** [comment]
Submit a trouble ticket and I’ll follow up directly.

Marlon

**Comment by marpierc** [comment]
Hi Pratik, Did this get resolved?

**Comment by patel99** [comment]
Not yet. One of the VM(CentOS) was activated one day later. But second one(Ubuntu) is not still activated.

**Comment by marpierc** [comment]
OK, keep filing the tickets.  Can you use Amazon?
