### ISSUE TITLE
Milestone 4: Some Additional Content

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/TeamAlpha#35]
Your code for Milestone 4 is working fine but you need to provide some additional material to complete the assignment. From the Canvas description:
- Design and publish schema in GitHub for your metadata system.: Computing, applications, and experiments must be described.
- Design and publish a description of your information management system.

You can do this in the GitHub Wiki area and include pointers to GitHub entries, issues, etc.

**Comment by amrutakamat16** [comment]
Hello Marlon,

We have added information of our metadata system at the below location:

https://github.com/airavata-courses/TeamAlpha/wiki/Information-Metadata-System

You may now go ahead with grading for Milestone-4.
