### ISSUE TITLE
Jenkins Question

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/TeamAlpha#39]
Hi Team Alpha,

In your Milestone 5 Wiki instructions, you say "Click on 'Manage Jenkins' -> 'Configure System' then Enter your private key passphrase in CVS section".  Which private key is this and what is it used for? Does the public key need to be installed on another location? And why are you adding this to the CVS section if we are using Git?

**Comment by patel99** [comment]
Hi Marlon,

Yes we do not need CVS, We were initially setting up jenkins on localhost and not on VM. In that case we required CVS. I would edit the instructions.

Thanks.
