### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by arpiagariu** [airavata-courses/TeamAlpha#8]
1. I would be better if you have provided the .Jar file.
2. Use class.getResourceAsStream instead of FileInputStream for managing the resources. You can use the resources wrapped in Jar file. You don't need to explicitly place the resources in the same folder as Jar file.
   http://jayaniwithanawasam.blogspot.com/2014/02/better-approach-to-load-resources-using.html
3. Reduce the level or frequency of logs. Right now it is printing a lot of not necessary information to the console.
   [Logs.txt](https://github.com/airavata-courses/TeamAlpha/files/113275/Logs.txt)

**Comment by patel99** [comment]
1. Yeah you are right we should have pushed jar file to github as well
2. Are you talking about 'props' folder? If yes than that is the design choice we made.
   - We can not wrap configurations in the jar file as we needed to make job properties like number of nodes and wall time customizable, if we woul hard code it in the jar then user won't be able to customize it without rebuilding from source code.
3. We have set current logging mode to Debug, if we change it to Error then we won't get any unnecessary logs.
   Thanks for pointing out these things.
   If you think I have addressed all your concerns then please close the issue.
